### ISSUE TITLE
Issue in ./articles/KA-16550.md

### ISSUE THREAD

**Issue by ddarziu** [AdobeDocs/experience-cloud-kcs.en#15]
Step 4. from the Resolution section points to this page [https://helpx.adobe.com/experience-manager/kb/oak-blobstore-inconsistency-blobId.html] which is coming up as 404 Not Found.

**Comment by barnato-v** [comment]
@ddarziu Thank you for your contribution. I have created a Jira ticket  and I am checking with the original author of this article here https://jira.corp.adobe.com/browse/DXSKB-95

**Comment by barnato-v** [comment]
@ddarziu I have replaced the broken link. Thank you for your help. Closing this issue now.
