### ISSUE TITLE
Step 1 needs clarity

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-cloud-kcs.en#16]
Issue in ./articles/KA-21738.md

Step 1 states "Navigate to Web Console (http://localhost:4502/system/console) Status"
This is not a clear explanation of what the customer should do. What it should say is something like this:
1. Navigate to Web Console (http://localhost:4502/system/console)
In the "Status" menu are various items that will show the instance's status.

**Comment by jmenn** [comment]
Hi @johnb4 !

Thank you for your submission!

I see what you're saying. We'll check it out.

**Comment by jmenn** [comment]
Hi @johnb4 !

We've edited the article.
https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-21738.html  
Thank you again!
