### ISSUE TITLE
Article KA-19022 Needs to be Archived since it's already been archived in Dynamics

### ISSUE THREAD

**Issue by jmenn** [AdobeDocs/experience-cloud-kcs.en#17]
Issue in ./articles/KA-19022.md

Per IT Support/Anushree Chaturvedi (anushreec@adobe.com), this article KA-19022 needs to be archived from ExL likewise because it has been archived from the Dynamics end since 10/8/2022:

Screenshot proof:
![4D5871012B0A41618FBF7E3183D00FF1](https://github.com/AdobeDocs/experience-cloud-kcs.en/assets/68084986/44ee748b-6ba1-4d84-8e6f-1c622592a8db)

"As we can see articles has been archived in dynamics that is the reason you are not able to see articles in all articles view."

Please let me know when this has been completed.
Thank you!

**Comment by bbringhu** [comment]
https://git.corp.adobe.com/AdobeDocs/experience-cloud-kcs.en/pull/2745

**Comment by bbringhu** [comment]
Removed
