### ISSUE TITLE
Misleading information in document

### ISSUE THREAD

**Issue by deepankarcouncil** [AdobeDocs/experience-cloud-kcs.en#19]
Issue in ./articles/KA-19448.md

Related reading point 3 

_Troubleshooting Developer Console access (https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/debugging/debugging-aem-as-a-cloud-service/developer-console.html?lang=en#troubleshooting-developer-console-access)_

points to troubleshooting developer console access, which is AEM's developer console. Not Adobe I/O developer console. This document 

_https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-19448.html?lang=en#:~:text=Access%20is%20enabled%20by%20granting,the%20user%20who%20needs%20access._ 

 is about Adobe I/O developer console. So **this information is misleading**

**Comment by jmenn** [comment]
Hi @deepankarcouncil!

Thank you for making a comment!

We will take a look.

**Comment by jmenn** [comment]
Hi @deepankarcouncil!

Please click on the "Detailed Feedback Options" at the bottom of the page you referenced:
https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/debugging/debugging-aem-as-a-cloud-service/overview.html 
so the team that manages those pages can consider your suggestion.

Thank you again for submitting a comment!

**Comment by deepankarcouncil** [comment]
But the issue is on this document - 

https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-19448.html?lang=en#:~:text=Troubleshooting%20Developer%20Console%20access%20(https%3A//experienceleague.adobe.com/docs/experience%2Dmanager%2Dlearn/cloud%2Dservice/debugging/debugging%2Daem%2Das%2Da%2Dcloud%2Dservice/developer%2Dconsole.html%3Flang%3Den%23troubleshooting%2Ddeveloper%2Dconsole%2Daccess)

**Comment by barnato-v** [comment]
@jmenn Hi Jim, I think the issue that @deepankarcouncil was commenting on was a link to AEM documentation in a KCS article that was on Adobe I/O developer console.

**Comment by barnato-v** [comment]
Hello @deepankarcouncil and @jmenn 

Changes were made to the following article in line with the contribute @deepankarcouncil suggestions and the appropriate SME https://developer.adobe.com/developer-console/docs/support/faq/#why-cant-i-create-a-project-for-my-organization

I believe I have made the necessary changes and will close this ticket.

**Comment by deepankarcouncil** [comment]
Thanks @barnato-v looks correct now!
