### ISSUE TITLE
Package attachment is missing in this page.

### ISSUE THREAD

**Issue by avrt** [AdobeDocs/experience-cloud-kcs.en#2]
Issue in ./articles/KA-17628.md

Package attachment is missing here.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/39145769/193178469-3c40f0d2-a58e-46bb-80d2-fda73ee8030e.png">

There is no link to attachment as described in the screenshot.

**Comment by almarchenko** [comment]
Thank you @avrt , we created an internal ticket to look at it.

**Comment by almarchenko** [comment]
Done

**Comment by jmenn** [comment]
Hi @avrt!
The package attachment has been re-attached on that article:
https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-17628.html

The link to the package is attached to the "attached package" in the first bullet in the Resolution instructions.
