### ISSUE TITLE
The resolution is just a more explicit formulation of the problem. 

### ISSUE THREAD

**Issue by patrick-schindler** [AdobeDocs/experience-cloud-kcs.en#21]
Issue in ./articles/KA-19240.md

The article describes a situation / problem, but gives no resolution. 
It is an explicit formulation of the problem, but provides no help to authors or developers. 
There are real-live cases where the permission to replicate is not wanted (e.g. for the blueprint in a msm setup), but deletion is required. 
Why is the possibility to delete a page dependent on the replication permission?

**Comment by almarchenko** [comment]
@patrick-schindler  thank you for your feedback. 
>Why is the possibility to delete a page dependent on the replication permission?
This is not something we can address as content authors. This is a product improvement request.
