### ISSUE TITLE
Demo Package Is Not Usable

### ISSUE THREAD

**Issue by friendlymahi** [AdobeDocs/experience-cloud-kcs.en#22]
Issue in ./articles/KA-17481.md

Zip gets downloaded, but I am unable to extract it. I am using a Mac with M1 chip.

Thanks !

**Comment by almarchenko** [comment]
Hi @friendlymahi ! Thank you for the feedback!
We'll check why is that.

**Comment by barnato-v** [comment]
Hi @friendlymahi! The article was updated with steps to download the file and extract on Mac.  Did they resolve your issue? See updated article here https://experienceleague.adobe.com/en/docs/experience-cloud-kcs/kbarticles/ka-17481

**Comment by barnato-v** [comment]
Closing as assumed demo package issue has been fixed.
