### ISSUE TITLE
Screen shot is not displayed correctly

### ISSUE THREAD

**Issue by dymori** [AdobeDocs/experience-cloud-kcs.en#24]
Issue in ./articles/KA-17461.md

Hello,

It seems like the screenshot near the top of the page is not displaying.
![image](https://github.com/AdobeDocs/experience-cloud-kcs.en/assets/7588477/b9663507-a899-482b-bc75-426e0df2efdf)

It would be great if this can be looked at! Thank you in advance.

**Comment by jmenn** [comment]
Hi @dymori!

Thanks for you submission!

It looks like this has been fixed -- the picture renders now.

Thank you again!
