### ISSUE TITLE
Workflows with JavaScript “IOB-090013 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed”

### ISSUE THREAD

**Issue by senthilGITrepo** [AdobeDocs/experience-cloud-kcs.en#4]
I have seen the solution as update customer.sh with WPP_SSL_ALLOW_INSECURE environment set to 1. where is the file located? Adobe campaign servers are running in windows

**Comment by almarchenko** [comment]
@senthilGITrepo  I'm sorry for missing this. Could you please provide a link to the article in question?

**Comment by barnato-v** [comment]
@senthilGITrepo Hi! thanks for submitting this. Would you mind providing us a link to the article?

I have tried searching for the article you want to change by searching for the error message you provided when you opened this issue - however I cannot find the correct article. Would you mind helping us identify the article or unfortunately I will have to close this issue.

**Comment by almarchenko** [comment]
Closing this since we didn't get the response.
